version: '3'
services:
  app:
    image: vue-docker-image
    container_name: vue-docker
    ports:
      - 4000:3000
    volumes:
      - .:/vue-cli-todo-app
    environment:
      - NODE_ENV=development